# Railway Configuration - Deploy Backend from Root
[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "never"
  startCommand = "java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar app.jar"
