services:
  - type: web
    name: linkedin-content-generator
    env: docker
    repo: https://github.com/itsmesuraj20/linkedin-content-generator.git
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USER  
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: PORT
        value: 8080
