services:
  - type: web
    name: linkedin-content-generator-backend
    env: java
    repo: https://github.com/itsmesuraj20/linkedin-content-generator.git
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/linkedin-content-generator-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: DATABASE_URL
        value: postgresql://username:password@hostname:port/database
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
